from django.urls import path

from recuperari.views import (
    CourseScheduleDetailView,
    CoursesList,
    MakeUpsListView,
    MakeUpRequestNewView,
    MakeUpSessionsAvailableView,
    ResetPasswordView,
    SchoolSetupView,
    SendEmailToGroupsView,
    SessionDescriptionList,
    SessionInfoList,
    SignInView,
    StudentProfileView,
    TrainerProfileView,
    TrainerScheduleView,
    UploadCourseExcelView,
    UploadStudentsExcelView,
    UploadStudentCourseScheduleFirstDayView,
    StudentCreateView,
    StudentFirstDayListView,
    TrainerCreateView,
    SessionsListView,
    SignOutView,
    StudentAbsentView,
)

urlpatterns = [
    path('courses/', CoursesList.as_view(), name='courses-list'),
    path(
        'course_sessions/<uuid:pk>/',
        SessionInfoList.as_view(),
        name='session_list'
    ),
    path(
        'sessions/', SessionsListView.as_view(),
    ),
    path(
        'session/description/<uuid:course_id>/',
        SessionDescriptionList.as_view(),
        name='session_description_list',
    ),
    path(
        'trainer_schedule/<uuid:pk>/',
        TrainerScheduleView.as_view(),
        name='trainer_schedule',
    ),
    path(
        "make_ups/",
        MakeUpsListView.as_view(),
    ),
    path(
        "get_available_make_ups/",
        MakeUpSessionsAvailableView.as_view(),
        name="get_make_ups_for_session",
    ),
    path(
        "request_make_up/",
        MakeUpRequestNewView.as_view(),
        name="request_make_up",
    ),
    path(
        "student_absent/<uuid:student_id>/<uuid:session_id>/",
        StudentAbsentView.as_view(),
    ),
    path(
        "course_excel_upload/",
        UploadCourseExcelView.as_view(),
        name="course_excel_upload"
    ),
    path(
        "students_excel_upload/",
        UploadStudentsExcelView.as_view(),
        name="students_excel_upload"
    ),
    path(
        "student_excel_first_day_upload/",
        UploadStudentCourseScheduleFirstDayView.as_view(),
    ),
    path(
        "course_schedule_details/",
        CourseScheduleDetailView.as_view(),
    ),
    path(
        "auth/login/",
        SignInView.as_view(),
        name="login",
    ),
    path(
        "auth/logout/",
        SignOutView.as_view(),
    ),
    path(
        "auth/reset_password/",
        ResetPasswordView.as_view(),
        name="reset_password",
    ),
    path(
        "school-setup/",
        SchoolSetupView.as_view(),
        name="school-setup"
    ),
    path(
        "trainer-profile/<uuid:pk>",
        TrainerProfileView.as_view(),
        name="trainer-profile"
    ),
    path(
        "trainer-create",
        TrainerCreateView.as_view(),
        name="trainer-profile"
    ),
    path(
        "student-profile/<uuid:pk>",
        StudentProfileView.as_view(),
        name="student-profile"
    ),
    path(
        "student-create",
        StudentCreateView.as_view(),
        name="student-profile"
    ),
    path(
        "send-group-email",
        SendEmailToGroupsView.as_view(),
    ),
    path(
        'student-course-first-day/',
        StudentFirstDayListView.as_view(),
        name='student-course-first-day-list'),
]
