# Generated by Django 4.2.5 on 2023-10-07 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('course_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CourseDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('luni', 'Luni'), ('marti', 'Marti'), ('miercuri', 'Miercuri'), ('joi', 'Joi'), ('vineri', 'Vineri'), ('sambata', 'Sambata'), ('duminica', 'Duminica')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CourseDescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('short_description', models.TextField(max_length=100)),
                ('long_description', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=50)),
                ('total_sessions', models.SmallIntegerField()),
                ('first_day_of_session', models.DateField()),
                ('last_day_of_session', models.DateField()),
                ('day', models.CharField(max_length=15)),
                ('time', models.TimeField()),
                ('course_type', models.CharField(choices=[('onl', 'Online'), ('hbr', 'Hibrid'), ('grp', 'Group')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recuperari.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('participant_name', models.CharField(max_length=50)),
                ('participant_parent_name', models.CharField(max_length=50)),
                ('parent_phone_number', models.CharField(max_length=20)),
                ('parent_email', models.CharField(max_length=50)),
                ('submission_state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone_contact', models.CharField(max_length=15)),
                ('email_contact', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('available_from', models.DateField()),
                ('available_to', models.DateField()),
                ('available_hour_from', models.TimeField()),
                ('available_hour_to', models.TimeField()),
                ('available_for', models.CharField(choices=[('course', 'Course'), ('make_up', 'Make Up Session')], max_length=50)),
                ('available_days', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recuperari.coursedays')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recuperari.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='SessionsDescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('min_session_no_description', models.IntegerField()),
                ('max_session_no_description', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recuperari.course')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('session_passed', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('session_no', models.SmallIntegerField()),
                ('made_up', models.BooleanField(default=False)),
                ('absent_participants', models.ManyToManyField(to='recuperari.student')),
                ('course_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recuperari.courseschedule')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone_contact', models.CharField(max_length=15)),
                ('email_contact', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_school', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MakeUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('make_up_on', models.DateTimeField()),
                ('type', models.CharField(choices=[('online_with_other_class', 'Online cu alta grupa'), ('online_make_up', 'Recuperare online'), ('on_stie_with_other_class', 'La sediu cu alta grupa'), ('on_stie_make_up', 'Recuperare la sediu')], max_length=50)),
                ('duration_in_minutes', models.SmallIntegerField(default=30)),
                ('make_up_for_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recuperari.session')),
                ('make_up_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recuperari.course')),
                ('make_up_trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recuperari.trainer')),
            ],
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='students',
            field=models.ManyToManyField(to='recuperari.student'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='trainer',
            field=models.ManyToManyField(to='recuperari.trainer'),
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_school', to='recuperari.school'),
        ),
    ]
