# Generated by Django 4.2.5 on 2023-10-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperari', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourseschedule',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
