# Generated by Django 4.2.5 on 2023-12-12 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recuperari', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_school', to=settings.AUTH_USER_MODEL),
        ),
    ]
