# Generated by Django 4.2.5 on 2023-10-27 09:47

from django.db import migrations, models
import django.db.models.deletion
import encrypted_field.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recuperari', '0002_alter_studentcourseschedule_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='room_count',
        ),
        migrations.AddField(
            model_name='school',
            name='cif',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='smart_bill_api_key',
            field=encrypted_field.fields.EncryptedField(default='001|a8f2aedcbe8ac307e3eba23921d4a9d7'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.PositiveIntegerField()),
                ('invoice_series', models.CharField(max_length=10)),
                ('invoice_for_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_invoices', to='recuperari.student')),
            ],
        ),
    ]
