# Generated by Django 4.2.5 on 2023-10-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperari', '0002_remove_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='room_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
