# Generated by Django 4.2.5 on 2023-10-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperari', '0002_alter_course_school_alter_courseschedule_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerschedule',
            name='available_for',
        ),
        migrations.AddField(
            model_name='trainerschedule',
            name='available_for_course',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trainerschedule',
            name='available_for_make_up',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trainerschedule',
            name='online_only',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='trainerschedule',
            name='available_days',
        ),
        migrations.AddField(
            model_name='trainerschedule',
            name='available_days',
            field=models.ManyToManyField(to='recuperari.coursedays'),
        ),
    ]
