# Generated by Django 4.2.5 on 2023-10-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperari', '0003_alter_makeup_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeup',
            name='make_up_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='makeup',
            name='type',
            field=models.CharField(blank=True, choices=[('onl', 'Online cu alta grupa'), ('online_make_up', 'Recuperare online'), ('sed', 'La sediu cu alta grupa'), ('hbr', 'Hibrid cu alta grupa'), ('on_site_make_up', 'Recuperare la sediu')], max_length=50, null=True),
        ),
    ]
