# Generated by Django 4.2.5 on 2023-10-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperari', '0003_remove_trainerschedule_available_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='can_have_on_site_make_up',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='session',
            name='can_have_online_make_up',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='makeup',
            name='type',
            field=models.CharField(choices=[('onl', 'Online cu alta grupa'), ('online_make_up', 'Recuperare online'), ('grp', 'La sediu cu alta grupa'), ('hbr', 'Hibrid cu alta grupa'), ('on_stie_make_up', 'Recuperare la sediu')], max_length=50),
        ),
    ]
