# Generated by Django 4.2.5 on 2023-10-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperari', '0003_school_room_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='room_count',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
