# Generated by Django 4.2.5 on 2023-10-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperari', '0004_alter_school_room_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_reset_password_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
