# Generated by Django 4.2.5 on 2023-12-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperari', '0005_daysoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='email1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
