# Generated by Django 4.2.5 on 2023-10-09 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recuperari', '0005_alter_course_id_alter_coursedescription_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerschedule',
            name='school',
            field=models.ForeignKey(default='2d3db5ad-b3da-46f8-9d4b-0e65fdbe2f30', on_delete=django.db.models.deletion.CASCADE, to='recuperari.school'),
            preserve_default=False,
        ),
    ]
