# Generated by Django 4.2.5 on 2023-10-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperari', '0005_user_is_reset_password_needed_alter_trainer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_reset_password_email_token_expired',
            field=models.BooleanField(default=True),
        ),
    ]
