# Generated by Django 4.2.5 on 2023-10-18 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recuperari', '0005_user_is_reset_password_needed_alter_trainer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeksOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
