# Generated by Django 4.2.5 on 2023-10-19 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recuperari', '0006_user_is_reset_password_email_token_expired'),
        ('recuperari', '0006_weeksoff'),
    ]

    operations = [
    ]
