# Generated by Django 4.2.5 on 2023-12-13 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recuperari', '0006_alter_parent_email1_alter_parent_phone_number1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='course_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='recuperari.courseschedule'),
        ),
    ]
