# Generated by Django 4.2.5 on 2023-10-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperari', '0006_user_is_reset_password_email_token_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='students',
            field=models.ManyToManyField(related_name='course_schedule_students', to='recuperari.student'),
        ),
    ]
