# Generated by Django 4.2.5 on 2023-10-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperari', '0006_trainerschedule_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makeup',
            name='make_up_group',
        ),
        migrations.AddField(
            model_name='makeup',
            name='make_up_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='makeup',
            name='make_up_completed',
            field=models.BooleanField(default=False),
        ),
    ]
