# Generated by Django 4.2.5 on 2023-10-19 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recuperari', '0007_merge_20231019_2354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeeksOff',
        ),
    ]
