# Generated by Django 4.2.5 on 2023-12-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recuperari', '0007_alter_session_course_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absentstudent',
            name='is_absent_completed',
        ),
        migrations.RemoveField(
            model_name='absentstudent',
            name='is_absent_for_make_up',
        ),
    ]
