# Generated by Django 4.2.5 on 2023-10-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperari', '0007_remove_makeup_make_up_group_makeup_make_up_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='next_possible_course',
            field=models.ManyToManyField(blank=True, related_name='next_course', to='recuperari.course'),
        ),
    ]
