# Generated by Django 4.2.5 on 2023-10-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperari', '0007_alter_courseschedule_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_active',
            field=models.BooleanField(default=True),
        ),
    ]
