# Generated by Django 4.2.5 on 2023-10-25 15:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recuperari', '0008_delete_weeksoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
            ],
        ),
    ]
