# Generated by Django 4.2.5 on 2023-10-09 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recuperari', '0008_course_next_possible_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedescription',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recuperari.course'),
            preserve_default=False,
        ),
    ]
