# Generated by Django 4.2.5 on 2023-12-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperari', '0008_remove_absentstudent_is_absent_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absentstudent',
            name='is_make_up_on_site',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='absentstudent',
            name='is_make_up_online',
            field=models.BooleanField(default=False),
        ),
    ]
