# Generated by Django 4.2.5 on 2023-10-13 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recuperari', '0009_coursedescription_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='submission_state',
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(default='2d3db5ad-b3da-46f8-9d4b-0e65fdbe2f30', on_delete=django.db.models.deletion.CASCADE, related_name='school_students', to='recuperari.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_description', to='recuperari.course'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='course_type',
            field=models.CharField(choices=[('onl', 'Online'), ('hbr', 'Hibrid'), ('sed', 'Sediu')], max_length=10),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='day',
            field=models.CharField(choices=[('luni', 'Luni'), ('marti', 'Marti'), ('miercuri', 'Miercuri'), ('joi', 'Joi'), ('vineri', 'Vineri'), ('sambata', 'Sambata'), ('duminica', 'Duminica')], max_length=15),
        ),
        migrations.AlterField(
            model_name='makeup',
            name='make_up_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recuperari.trainer'),
        ),
        migrations.AlterField(
            model_name='makeup',
            name='type',
            field=models.CharField(choices=[('onl', 'Online cu alta grupa'), ('online_make_up', 'Recuperare online'), ('sed', 'La sediu cu alta grupa'), ('hbr', 'Hibrid cu alta grupa'), ('on_stie_make_up', 'Recuperare la sediu')], max_length=50),
        ),
    ]
