# Generated by Django 4.2.5 on 2023-10-09 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recuperari', '0009_coursedescription_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedescription',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_description', to='recuperari.course'),
        ),
        migrations.AlterField(
            model_name='makeup',
            name='make_up_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recuperari.trainer'),
        ),
    ]
